### ISSUE TITLE
Change ordering of libraries in Python webinar

### ISSUE THREAD

**Issue by ashwinvis** [ENCCS/webinar_documents#2]
The course shows some CUDA code in the very beginning. Since it is an intro course, it should appear easier.

I would suggest show high level implementations first, then low level. Therefore go in this order,

1. cuDF (heterogenous dataframes! but what if we are interested in only arrays...)
2. Numba
3. Jax
4. Cupy (what if an algorithm does not exist in the above libraries, we go low-level)
5. PyCUDA

Does that sound good @code4yonglei ?

**Comment by ashwinvis** [comment]
@code4yonglei gentle reminder

**Comment by code4yonglei** [comment]
@ashwinvis You can rearrange these parts based on any orders. I am totaly fine with these rearrangement.
